### ISSUE TITLE
code reviewer

### ISSUE THREAD

**Issue by ReAliens** [ReAliens/Speedy#19]
this issue is for code reviewer 
we are consist of four developers
![Screenshot from 2022-04-28 11-46-34](https://user-images.githubusercontent.com/51102661/165726230-861780ce-7df6-47d1-823c-ba3f7a53d531.png)
![Screenshot from 2022-04-28 11-46-29](https://user-images.githubusercontent.com/51102661/165726236-1f2185e7-58e8-4576-8ed2-3576993bae6d.png)

**Comment by MuriloRoque** [comment]
Hi @ReAliens, @mahbubul14, @yahyaelganyni1, @Mucyosoda,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
